### PR TITLE
Support Faraday 1.x too

### PR DESCRIPTION
**Pull request by jrochkind**
To allow a dependency that uses redirect middleware to work with either faraday 1.x or 2.x.

I manually ran tests with both faraday 1.0.0 and 1.10.0 (latest 1.x) -- and tests were green with both! So, if we can trust the tests, this already appears to work fine with faraday 1.x -- having the gemspec allow 1.x will allow a gem that depends on faraday to do redirection while allowing the consuming app to use either faraday 1.x or 2.x. 

I am finding it's very hard to get all my dependencies allowing faraday 2.x, so I think it's necessary for gems to support 1.x and 2.x for a bit, to try to get people to being able to upgrade to 2.x, while different people will be able to at different times. 

Theoretically we could adopt the github actions CI to test with both faraday 1.x and 2.x, but I didn't do that here, I thought maybe it wasn't necessary. If it were, I think I'd probably add the [appraisal](https://github.com/thoughtbot/appraisal) gem for that. Let me know if you require it.

### CODE REVIEW

**Comment by tisba** [comment]
Hey! Thanks for the PR.

I think I do want tests with faraday 1.x and 2.x. If you could take a stab on that, that would be great (have very little time in the next days 😢).

**Comment by jrochkind** [comment]
OK, i'll see what I can do!  You don't mind if I use the appraisal gem? While it's theoretically possible to do otherwise, I've found this to be the least confusing/gotcha way to do it.

Is latest faraday 1.x enough, or should we also test on 1.0.0?  I did a manual test on 1.0.0 myself just to be *sure*, in case something had changed between then and latest 1.x that would effect compatibility... not sure if it's necessary to have two 1.x's in CI though.

**Comment by jrochkind** [comment]
OK, here is one way to do it anyway. I think it worked out pretty well actually. 

@tisba it's not running CI here yet since I'm a first time contributor awaiting approval to run the workflow, you need to click something somewhere for it to run the CI here... I think it'll pass... if faraday 1.x doesn't work with ruby 3.1 though, then that'll require much more complicated setup.

**Comment by iMacTia** [comment]
@jrochkind something I did in the past was adding the different gemfiles to the GitHub matrix (see [example here](https://github.com/iMacTia/lograge-sql/blob/master/.github/workflows/ci.yml#L32)). This allows you only run the matrix where you need it, exclude the pair you don't need to support, avoid duplicate linter runs and dependencies on external gems. Might be another good alternative

**Comment by jrochkind** [comment]
Hm, not sure why tests are failing -- they pass for me locally doing the same thing I thought CI was doing. 

> something I did in the past was adding the different gemfiles to the GitHub matrix (see [example here](https://github.com/iMacTia/lograge-sql/blob/master/.github/workflows/ci.yml#L32)). This allows you only run the matrix where you need it, exclude the pair you don't need to support, avoid duplicate linter runs and dependencies on external gems. Might be another good alternative

I think what I ended up with allows all those things too. But would you prefer that approach to what I have here?  Not sure when I'll have time, but I can try it. I thought adding to matrix would result in duplicate linter runs but I can look at your example. Are you still okay with using appraisal to manage the gemfiles? 

I think what I have here might be okay though?

**Comment by jrochkind** [comment]
Weird, the build is failing on something in the gemspec that this PR didn't touch. I dunno but I can fix that.

**Comment by jrochkind** [comment]
I rebased on main, which maybe will resolve the rubocop problem... but it looks like it's refusing to run CI again? "First-time contributors need a maintainer to approve running workflows.".  I dunno!

**Comment by jrochkind** [comment]
OK, I still don't understand why rubocop is complaining about a line that this PR didn't change -- did you manage to get something in main branch that rubocop doesn't like? Should I fix it here? I guess i'll try!

**Comment by jrochkind** [comment]
Sorry, would someone mind triggering CI on this again so we can see if I've made rubocop happy? Thanks!

**Comment by jrochkind** [comment]
Thanks! I'll look at it and try again. 

It all works just fine on my local machine -- rubocop and specs both. So it's challenging to have to debug via trying something else pushing then asking you to push the button again!

**Comment by jrochkind** [comment]
oh okay, the `appraisal` approach to testing multiple versions of faraday is for some reason failing when run on github actions, even though it works just fine for me locally. 

that's weird, and I don't know how to debug... except trying to use a different mechanism entirely of testing the multiple dependencies, I guess. 

I may have another hour or two to spend on this tomorrow, but I'm running out of time (for the next few weeks at least). Isn't it crazy how fighting with CI can take 5-10x as much time as the actual code change? the actual code change here was trivial, and I've spent a bunch of time fighting with the CI!

**Comment by jrochkind** [comment]
OK, sorry for so many comments... I think I understand why what I did isn't going to work on CI, and think I can make it work, give me one more try!

**Comment by jrochkind** [comment]
WOO, all checks passed!

**Comment by tisba** [comment]
Thanks for working on this, @jrochkind 🙇

**Comment by tisba** [comment]
just pushed 0.3.0 to rubygems

**Pull request merged**
